/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TimetableRouteImport } from "./routes/timetable"
import { Route as SubmitCaseRouteImport } from "./routes/submit-case"
import { Route as PracticeRouteImport } from "./routes/practice"
import { Route as NewsRouteImport } from "./routes/news"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as LeaderboardRouteImport } from "./routes/leaderboard"
import { Route as JoinRouteImport } from "./routes/join"
import { Route as EventsRouteImport } from "./routes/events"
import { Route as DeadlinesRouteImport } from "./routes/deadlines"
import { Route as CasesRouteImport } from "./routes/cases"
import { Route as AlumniRouteImport } from "./routes/alumni"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as AccountRouteImport } from "./routes/account"
import { Route as IndexRouteImport } from "./routes/index"

const TimetableRoute = TimetableRouteImport.update({
  id: "/timetable",
  path: "/timetable",
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitCaseRoute = SubmitCaseRouteImport.update({
  id: "/submit-case",
  path: "/submit-case",
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: "/practice",
  path: "/practice",
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: "/news",
  path: "/news",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: "/leaderboard",
  path: "/leaderboard",
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: "/join",
  path: "/join",
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: "/deadlines",
  path: "/deadlines",
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: "/cases",
  path: "/cases",
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: "/alumni",
  path: "/alumni",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/admin": typeof AdminRoute
  "/alumni": typeof AlumniRoute
  "/cases": typeof CasesRoute
  "/deadlines": typeof DeadlinesRoute
  "/events": typeof EventsRoute
  "/join": typeof JoinRoute
  "/leaderboard": typeof LeaderboardRoute
  "/login": typeof LoginRoute
  "/news": typeof NewsRoute
  "/practice": typeof PracticeRoute
  "/submit-case": typeof SubmitCaseRoute
  "/timetable": typeof TimetableRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/admin": typeof AdminRoute
  "/alumni": typeof AlumniRoute
  "/cases": typeof CasesRoute
  "/deadlines": typeof DeadlinesRoute
  "/events": typeof EventsRoute
  "/join": typeof JoinRoute
  "/leaderboard": typeof LeaderboardRoute
  "/login": typeof LoginRoute
  "/news": typeof NewsRoute
  "/practice": typeof PracticeRoute
  "/submit-case": typeof SubmitCaseRoute
  "/timetable": typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/admin": typeof AdminRoute
  "/alumni": typeof AlumniRoute
  "/cases": typeof CasesRoute
  "/deadlines": typeof DeadlinesRoute
  "/events": typeof EventsRoute
  "/join": typeof JoinRoute
  "/leaderboard": typeof LeaderboardRoute
  "/login": typeof LoginRoute
  "/news": typeof NewsRoute
  "/practice": typeof PracticeRoute
  "/submit-case": typeof SubmitCaseRoute
  "/timetable": typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/account"
    | "/admin"
    | "/alumni"
    | "/cases"
    | "/deadlines"
    | "/events"
    | "/join"
    | "/leaderboard"
    | "/login"
    | "/news"
    | "/practice"
    | "/submit-case"
    | "/timetable"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/account"
    | "/admin"
    | "/alumni"
    | "/cases"
    | "/deadlines"
    | "/events"
    | "/join"
    | "/leaderboard"
    | "/login"
    | "/news"
    | "/practice"
    | "/submit-case"
    | "/timetable"
  id:
    | "__root__"
    | "/"
    | "/account"
    | "/admin"
    | "/alumni"
    | "/cases"
    | "/deadlines"
    | "/events"
    | "/join"
    | "/leaderboard"
    | "/login"
    | "/news"
    | "/practice"
    | "/submit-case"
    | "/timetable"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AlumniRoute: typeof AlumniRoute
  CasesRoute: typeof CasesRoute
  DeadlinesRoute: typeof DeadlinesRoute
  EventsRoute: typeof EventsRoute
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  PracticeRoute: typeof PracticeRoute
  SubmitCaseRoute: typeof SubmitCaseRoute
  TimetableRoute: typeof TimetableRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/timetable": {
      id: "/timetable"
      path: "/timetable"
      fullPath: "/timetable"
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/submit-case": {
      id: "/submit-case"
      path: "/submit-case"
      fullPath: "/submit-case"
      preLoaderRoute: typeof SubmitCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/practice": {
      id: "/practice"
      path: "/practice"
      fullPath: "/practice"
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/news": {
      id: "/news"
      path: "/news"
      fullPath: "/news"
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/leaderboard": {
      id: "/leaderboard"
      path: "/leaderboard"
      fullPath: "/leaderboard"
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/join": {
      id: "/join"
      path: "/join"
      fullPath: "/join"
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/events": {
      id: "/events"
      path: "/events"
      fullPath: "/events"
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deadlines": {
      id: "/deadlines"
      path: "/deadlines"
      fullPath: "/deadlines"
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cases": {
      id: "/cases"
      path: "/cases"
      fullPath: "/cases"
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/alumni": {
      id: "/alumni"
      path: "/alumni"
      fullPath: "/alumni"
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account": {
      id: "/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AlumniRoute: AlumniRoute,
  CasesRoute: CasesRoute,
  DeadlinesRoute: DeadlinesRoute,
  EventsRoute: EventsRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  PracticeRoute: PracticeRoute,
  SubmitCaseRoute: SubmitCaseRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
